# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_business.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_business(object):
    def setupUi(self, business):
        business.setObjectName("business")
        business.resize(1185, 851)
        business.setStyleSheet("")
        self.scrollArea = QtWidgets.QScrollArea(business)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1200, 1000))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 2000, 1500))
        self.scrollAreaWidgetContents.setStyleSheet("#scrollAreaWidgetContents {border-image: url(:/2.jpg);}\n"
"\n"
"")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.statistics = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.statistics.setGeometry(QtCore.QRect(560, 110, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.statistics.setFont(font)
        self.statistics.setStyleSheet("color:rgb(200, 84, 6)")
        self.statistics.setObjectName("statistics")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(530, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("color:red")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(530, 540, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(520, 200, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.loan = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.loan.setGeometry(QtCore.QRect(60, 250, 1051, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loan.setFont(font)
        self.loan.setObjectName("loan")
        self.loan.setColumnCount(2)
        self.loan.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.loan.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.loan.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.loan.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.loan.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.loan.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.loan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.loan.setHorizontalHeaderItem(1, item)
        self.loan.horizontalHeader().setDefaultSectionSize(330)
        self.choice = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.choice.setGeometry(QtCore.QRect(450, 110, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.choice.setFont(font)
        self.choice.setObjectName("choice")
        self.choice.addItem("")
        self.choice.addItem("")
        self.choice.addItem("")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(530, 880, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.save = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.save.setGeometry(QtCore.QRect(60, 600, 1051, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save.setFont(font)
        self.save.setObjectName("save")
        self.save.setColumnCount(2)
        self.save.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.save.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.save.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.save.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.save.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.save.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.save.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.save.setHorizontalHeaderItem(1, item)
        self.save.horizontalHeader().setDefaultSectionSize(330)
        self.client_num = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.client_num.setGeometry(QtCore.QRect(60, 950, 1051, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.client_num.setFont(font)
        self.client_num.setObjectName("client_num")
        self.client_num.setColumnCount(2)
        self.client_num.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.client_num.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.client_num.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.client_num.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.client_num.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.client_num.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.client_num.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.client_num.setHorizontalHeaderItem(1, item)
        self.client_num.horizontalHeader().setDefaultSectionSize(330)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(business)
        QtCore.QMetaObject.connectSlotsByName(business)

    def retranslateUi(self, business):
        _translate = QtCore.QCoreApplication.translate
        business.setWindowTitle(_translate("business", "Dialog"))
        self.statistics.setText(_translate("business", "统计"))
        self.label.setText(_translate("business", "业务统计"))
        self.label_3.setText(_translate("business", "储蓄业务："))
        self.label_2.setText(_translate("business", "贷款业务："))
        item = self.loan.verticalHeaderItem(0)
        item.setText(_translate("business", "1"))
        item = self.loan.verticalHeaderItem(1)
        item.setText(_translate("business", "2"))
        item = self.loan.verticalHeaderItem(2)
        item.setText(_translate("business", "3"))
        item = self.loan.verticalHeaderItem(3)
        item.setText(_translate("business", "4"))
        item = self.loan.verticalHeaderItem(4)
        item.setText(_translate("business", "5"))
        item = self.loan.horizontalHeaderItem(0)
        item.setText(_translate("business", "支行名称"))
        item = self.loan.horizontalHeaderItem(1)
        item.setText(_translate("business", "贷款金额"))
        self.choice.setItemText(0, _translate("business", "本月"))
        self.choice.setItemText(1, _translate("business", "本季度"))
        self.choice.setItemText(2, _translate("business", "本年"))
        self.label_4.setText(_translate("business", "用户数："))
        item = self.save.verticalHeaderItem(0)
        item.setText(_translate("business", "1"))
        item = self.save.verticalHeaderItem(1)
        item.setText(_translate("business", "2"))
        item = self.save.verticalHeaderItem(2)
        item.setText(_translate("business", "3"))
        item = self.save.verticalHeaderItem(3)
        item.setText(_translate("business", "4"))
        item = self.save.verticalHeaderItem(4)
        item.setText(_translate("business", "5"))
        item = self.save.horizontalHeaderItem(0)
        item.setText(_translate("business", "支行名称"))
        item = self.save.horizontalHeaderItem(1)
        item.setText(_translate("business", "新增储蓄金额"))
        item = self.client_num.verticalHeaderItem(0)
        item.setText(_translate("business", "1"))
        item = self.client_num.verticalHeaderItem(1)
        item.setText(_translate("business", "2"))
        item = self.client_num.verticalHeaderItem(2)
        item.setText(_translate("business", "3"))
        item = self.client_num.verticalHeaderItem(3)
        item.setText(_translate("business", "4"))
        item = self.client_num.verticalHeaderItem(4)
        item.setText(_translate("business", "5"))
        item = self.client_num.horizontalHeaderItem(0)
        item.setText(_translate("business", "支行名称"))
        item = self.client_num.horizontalHeaderItem(1)
        item.setText(_translate("business", "用户数"))
