# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createClient.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_createClient(object):
    def setupUi(self, createClient):
        createClient.setObjectName("createClient")
        createClient.resize(446, 589)
        createClient.setStyleSheet("#createClient{border-image:url(./1.jpg);}")
        self.phone = QtWidgets.QLineEdit(createClient)
        self.phone.setGeometry(QtCore.QRect(190, 192, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.phone.setFont(font)
        self.phone.setObjectName("phone")
        self.label_5 = QtWidgets.QLabel(createClient)
        self.label_5.setGeometry(QtCore.QRect(163, 52, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.CreateBtn = QtWidgets.QPushButton(createClient)
        self.CreateBtn.setGeometry(QtCore.QRect(190, 530, 221, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CreateBtn.setFont(font)
        self.CreateBtn.setAutoFillBackground(True)
        self.CreateBtn.setObjectName("CreateBtn")
        self.addr = QtWidgets.QLineEdit(createClient)
        self.addr.setGeometry(QtCore.QRect(190, 234, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addr.setFont(font)
        self.addr.setObjectName("addr")
        self.id = QtWidgets.QLineEdit(createClient)
        self.id.setGeometry(QtCore.QRect(190, 108, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.id.setFont(font)
        self.id.setText("")
        self.id.setObjectName("id")
        self.label_3 = QtWidgets.QLabel(createClient)
        self.label_3.setGeometry(QtCore.QRect(33, 192, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(createClient)
        self.label.setGeometry(QtCore.QRect(33, 108, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(createClient)
        self.label_4.setGeometry(QtCore.QRect(33, 234, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(createClient)
        self.label_2.setGeometry(QtCore.QRect(33, 150, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.name = QtWidgets.QLineEdit(createClient)
        self.name.setGeometry(QtCore.QRect(190, 150, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.contactEmail = QtWidgets.QLineEdit(createClient)
        self.contactEmail.setGeometry(QtCore.QRect(187, 362, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.contactEmail.setFont(font)
        self.contactEmail.setObjectName("contactEmail")
        self.contactRelation = QtWidgets.QLineEdit(createClient)
        self.contactRelation.setGeometry(QtCore.QRect(187, 400, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.contactRelation.setFont(font)
        self.contactRelation.setObjectName("contactRelation")
        self.contactPhone = QtWidgets.QLineEdit(createClient)
        self.contactPhone.setGeometry(QtCore.QRect(187, 320, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.contactPhone.setFont(font)
        self.contactPhone.setObjectName("contactPhone")
        self.label_6 = QtWidgets.QLabel(createClient)
        self.label_6.setGeometry(QtCore.QRect(30, 276, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(createClient)
        self.label_7.setGeometry(QtCore.QRect(30, 362, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(createClient)
        self.label_8.setGeometry(QtCore.QRect(30, 400, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.contactName = QtWidgets.QLineEdit(createClient)
        self.contactName.setGeometry(QtCore.QRect(187, 276, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.contactName.setFont(font)
        self.contactName.setText("")
        self.contactName.setObjectName("contactName")
        self.label_9 = QtWidgets.QLabel(createClient)
        self.label_9.setGeometry(QtCore.QRect(30, 320, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        self.retranslateUi(createClient)
        QtCore.QMetaObject.connectSlotsByName(createClient)

    def retranslateUi(self, createClient):
        _translate = QtCore.QCoreApplication.translate
        createClient.setWindowTitle(_translate("createClient", "Dialog"))
        self.label_5.setText(_translate("createClient", "创建客户"))
        self.CreateBtn.setText(_translate("createClient", "创建"))
        self.label_3.setText(_translate("createClient", "电话"))
        self.label.setText(_translate("createClient", "身份证号"))
        self.label_4.setText(_translate("createClient", "住址"))
        self.label_2.setText(_translate("createClient", "姓名"))
        self.label_6.setText(_translate("createClient", "联系人姓名"))
        self.label_7.setText(_translate("createClient", "联系人邮箱"))
        self.label_8.setText(_translate("createClient", "联系人关系"))
        self.label_9.setText(_translate("createClient", "联系人电话"))
