# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modifyClient.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class modifyClient(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(447, 601)
        Dialog.setStyleSheet("#Dialog {border-image:url(./1.jpg);}")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(36, 102, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(36, 144, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.contactPhone = QtWidgets.QLineEdit(Dialog)
        self.contactPhone.setGeometry(QtCore.QRect(190, 314, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.contactPhone.setFont(font)
        self.contactPhone.setObjectName("contactPhone")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(36, 228, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(166, 46, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(33, 270, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.ModifyBtn = QtWidgets.QPushButton(Dialog)
        self.ModifyBtn.setGeometry(QtCore.QRect(193, 524, 221, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ModifyBtn.setFont(font)
        self.ModifyBtn.setAutoFillBackground(True)
        self.ModifyBtn.setObjectName("ModifyBtn")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(33, 314, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.addr = QtWidgets.QLineEdit(Dialog)
        self.addr.setGeometry(QtCore.QRect(193, 228, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addr.setFont(font)
        self.addr.setObjectName("addr")
        self.contactRelation = QtWidgets.QLineEdit(Dialog)
        self.contactRelation.setGeometry(QtCore.QRect(190, 394, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.contactRelation.setFont(font)
        self.contactRelation.setObjectName("contactRelation")
        self.contactEmail = QtWidgets.QLineEdit(Dialog)
        self.contactEmail.setGeometry(QtCore.QRect(190, 356, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.contactEmail.setFont(font)
        self.contactEmail.setObjectName("contactEmail")
        self.name = QtWidgets.QLineEdit(Dialog)
        self.name.setGeometry(QtCore.QRect(193, 144, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.phone = QtWidgets.QLineEdit(Dialog)
        self.phone.setGeometry(QtCore.QRect(193, 186, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.phone.setFont(font)
        self.phone.setObjectName("phone")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(36, 186, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(33, 394, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(33, 356, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.contactName = QtWidgets.QLineEdit(Dialog)
        self.contactName.setGeometry(QtCore.QRect(190, 270, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.contactName.setFont(font)
        self.contactName.setText("")
        self.contactName.setObjectName("contactName")
        self.id = QtWidgets.QLabel(Dialog)
        self.id.setGeometry(QtCore.QRect(190, 100, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.id.setFont(font)
        self.id.setText("")
        self.id.setObjectName("id")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "身份证号"))
        self.label_2.setText(_translate("Dialog", "姓名"))
        self.label_4.setText(_translate("Dialog", "住址"))
        self.label_5.setText(_translate("Dialog", "修改客户"))
        self.label_6.setText(_translate("Dialog", "联系人姓名"))
        self.ModifyBtn.setText(_translate("Dialog", "修改"))
        self.label_9.setText(_translate("Dialog", "联系人电话"))
        self.label_3.setText(_translate("Dialog", "电话"))
        self.label_8.setText(_translate("Dialog", "联系人关系"))
        self.label_7.setText(_translate("Dialog", "联系人邮箱"))
