# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loanPay.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loanPay(object):
    def setupUi(self, loanPay):
        loanPay.setObjectName("loanPay")
        loanPay.resize(478, 577)
        loanPay.setStyleSheet("#loanPay {border-image:url(./1.jpg);}")
        self.label = QtWidgets.QLabel(loanPay)
        self.label.setGeometry(QtCore.QRect(170, 20, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:red")
        self.label.setObjectName("label")
        self.Ok = QtWidgets.QPushButton(loanPay)
        self.Ok.setGeometry(QtCore.QRect(340, 520, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Ok.setFont(font)
        self.Ok.setStyleSheet("color:rgb(85, 0, 0)")
        self.Ok.setObjectName("Ok")
        self.label_2 = QtWidgets.QLabel(loanPay)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.loan_id = QtWidgets.QLabel(loanPay)
        self.loan_id.setGeometry(QtCore.QRect(160, 100, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.loan_id.setFont(font)
        self.loan_id.setText("")
        self.loan_id.setObjectName("loan_id")
        self.label_3 = QtWidgets.QLabel(loanPay)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.bank = QtWidgets.QLabel(loanPay)
        self.bank.setGeometry(QtCore.QRect(160, 150, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.bank.setFont(font)
        self.bank.setText("")
        self.bank.setObjectName("bank")
        self.label_4 = QtWidgets.QLabel(loanPay)
        self.label_4.setGeometry(QtCore.QRect(20, 200, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.amount = QtWidgets.QLabel(loanPay)
        self.amount.setGeometry(QtCore.QRect(160, 200, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.amount.setFont(font)
        self.amount.setText("")
        self.amount.setObjectName("amount")
        self.label_5 = QtWidgets.QLabel(loanPay)
        self.label_5.setGeometry(QtCore.QRect(20, 250, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.amount_payed = QtWidgets.QLabel(loanPay)
        self.amount_payed.setGeometry(QtCore.QRect(160, 250, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.amount_payed.setFont(font)
        self.amount_payed.setText("")
        self.amount_payed.setObjectName("amount_payed")
        self.label_6 = QtWidgets.QLabel(loanPay)
        self.label_6.setGeometry(QtCore.QRect(20, 400, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pay = QtWidgets.QLineEdit(loanPay)
        self.pay.setGeometry(QtCore.QRect(160, 400, 131, 31))
        self.pay.setText("")
        self.pay.setObjectName("pay")
        self.label_7 = QtWidgets.QLabel(loanPay)
        self.label_7.setGeometry(QtCore.QRect(20, 300, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.client_id = QtWidgets.QLabel(loanPay)
        self.client_id.setGeometry(QtCore.QRect(160, 300, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.client_id.setFont(font)
        self.client_id.setText("")
        self.client_id.setObjectName("client_id")
        self.client_name = QtWidgets.QLabel(loanPay)
        self.client_name.setGeometry(QtCore.QRect(160, 350, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.client_name.setFont(font)
        self.client_name.setText("")
        self.client_name.setObjectName("client_name")
        self.label_8 = QtWidgets.QLabel(loanPay)
        self.label_8.setGeometry(QtCore.QRect(20, 350, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(loanPay)
        self.label_9.setGeometry(QtCore.QRect(20, 460, 401, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:blue")
        self.label_9.setObjectName("label_9")
        self.ts = QtWidgets.QLabel(loanPay)
        self.ts.setGeometry(QtCore.QRect(330, 400, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ts.setFont(font)
        self.ts.setStyleSheet("color:red")
        self.ts.setText("")
        self.ts.setObjectName("ts")

        self.retranslateUi(loanPay)
        QtCore.QMetaObject.connectSlotsByName(loanPay)

    def retranslateUi(self, loanPay):
        _translate = QtCore.QCoreApplication.translate
        loanPay.setWindowTitle(_translate("loanPay", "Dialog"))
        self.label.setText(_translate("loanPay", "支付贷款"))
        self.Ok.setText(_translate("loanPay", "确定"))
        self.label_2.setText(_translate("loanPay", "贷款号："))
        self.label_3.setText(_translate("loanPay", "发放机构："))
        self.label_4.setText(_translate("loanPay", "贷款金额："))
        self.label_5.setText(_translate("loanPay", "已发放金额："))
        self.label_6.setText(_translate("loanPay", "支付金额："))
        self.label_7.setText(_translate("loanPay", "贷款人id："))
        self.label_8.setText(_translate("loanPay", "贷款人姓名："))
        self.label_9.setText(_translate("loanPay", "(注：这里只显示一个贷款人信息)"))
