# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loanSearch.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_laonSearch(object):
    def setupUi(self, laonSearch):
        laonSearch.setObjectName("laonSearch")
        laonSearch.resize(1188, 852)
        self.scrollArea = QtWidgets.QScrollArea(laonSearch)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1200, 1000))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 2000, 1500))
        self.scrollAreaWidgetContents.setStyleSheet("#scrollAreaWidgetContents {border-image: url(:/2.jpg);}\n"
"")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.Search = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Search.setGeometry(QtCore.QRect(750, 100, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Search.setFont(font)
        self.Search.setStyleSheet("color:rgb(200, 84, 6)")
        self.Search.setObjectName("Search")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(530, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("color:red")
        self.label.setObjectName("label")
        self.pay = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.pay.setGeometry(QtCore.QRect(50, 930, 1051, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pay.setFont(font)
        self.pay.setObjectName("pay")
        self.pay.setColumnCount(5)
        self.pay.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.pay.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.pay.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.pay.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.pay.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.pay.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.pay.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.pay.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.pay.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.pay.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.pay.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.pay.setItem(0, 0, item)
        self.pay.horizontalHeader().setDefaultSectionSize(205)
        self.ts = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ts.setGeometry(QtCore.QRect(380, 150, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ts.setFont(font)
        self.ts.setStyleSheet("color:red")
        self.ts.setText("")
        self.ts.setObjectName("ts")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(530, 540, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.client = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.client.setGeometry(QtCore.QRect(60, 580, 1051, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.client.setFont(font)
        self.client.setObjectName("client")
        self.client.setColumnCount(4)
        self.client.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.client.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.client.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.client.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.client.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.client.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.client.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.client.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.client.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.client.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.client.setItem(0, 0, item)
        self.client.horizontalHeader().setDefaultSectionSize(250)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(520, 200, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.text = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.text.setGeometry(QtCore.QRect(500, 100, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text.setFont(font)
        self.text.setText("")
        self.text.setObjectName("text")
        self.loan = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.loan.setGeometry(QtCore.QRect(60, 250, 1051, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loan.setFont(font)
        self.loan.setObjectName("loan")
        self.loan.setColumnCount(4)
        self.loan.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.loan.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.loan.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.loan.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.loan.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.loan.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.loan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.loan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.loan.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.loan.setHorizontalHeaderItem(3, item)
        self.loan.horizontalHeader().setDefaultSectionSize(200)
        self.choice = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.choice.setGeometry(QtCore.QRect(360, 100, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.choice.setFont(font)
        self.choice.setObjectName("choice")
        self.choice.addItem("")
        self.choice.addItem("")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(530, 880, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(laonSearch)
        QtCore.QMetaObject.connectSlotsByName(laonSearch)

    def retranslateUi(self, laonSearch):
        _translate = QtCore.QCoreApplication.translate
        laonSearch.setWindowTitle(_translate("laonSearch", "Dialog"))
        self.Search.setText(_translate("laonSearch", "搜索"))
        self.label.setText(_translate("laonSearch", "贷款搜索"))
        item = self.pay.verticalHeaderItem(0)
        item.setText(_translate("laonSearch", "1"))
        item = self.pay.verticalHeaderItem(1)
        item.setText(_translate("laonSearch", "2"))
        item = self.pay.verticalHeaderItem(2)
        item.setText(_translate("laonSearch", "3"))
        item = self.pay.verticalHeaderItem(3)
        item.setText(_translate("laonSearch", "4"))
        item = self.pay.verticalHeaderItem(4)
        item.setText(_translate("laonSearch", "5"))
        item = self.pay.horizontalHeaderItem(0)
        item.setText(_translate("laonSearch", "账户号"))
        item = self.pay.horizontalHeaderItem(1)
        item.setText(_translate("laonSearch", "11"))
        item = self.pay.horizontalHeaderItem(2)
        item.setText(_translate("laonSearch", "户主1身份证"))
        item = self.pay.horizontalHeaderItem(3)
        item.setText(_translate("laonSearch", "户主1姓名"))
        item = self.pay.horizontalHeaderItem(4)
        item.setText(_translate("laonSearch", "户主2身份证"))
        __sortingEnabled = self.pay.isSortingEnabled()
        self.pay.setSortingEnabled(False)
        self.pay.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("laonSearch", "申请者信息："))
        item = self.client.verticalHeaderItem(0)
        item.setText(_translate("laonSearch", "1"))
        item = self.client.verticalHeaderItem(1)
        item.setText(_translate("laonSearch", "2"))
        item = self.client.verticalHeaderItem(2)
        item.setText(_translate("laonSearch", "3"))
        item = self.client.verticalHeaderItem(3)
        item.setText(_translate("laonSearch", "4"))
        item = self.client.verticalHeaderItem(4)
        item.setText(_translate("laonSearch", "5"))
        item = self.client.horizontalHeaderItem(0)
        item.setText(_translate("laonSearch", "账户号"))
        item = self.client.horizontalHeaderItem(1)
        item.setText(_translate("laonSearch", "户主1身份证"))
        item = self.client.horizontalHeaderItem(2)
        item.setText(_translate("laonSearch", "户主1姓名"))
        item = self.client.horizontalHeaderItem(3)
        item.setText(_translate("laonSearch", "户主2身份证"))
        __sortingEnabled = self.client.isSortingEnabled()
        self.client.setSortingEnabled(False)
        self.client.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("laonSearch", "贷款信息："))
        item = self.loan.verticalHeaderItem(0)
        item.setText(_translate("laonSearch", "1"))
        item = self.loan.verticalHeaderItem(1)
        item.setText(_translate("laonSearch", "2"))
        item = self.loan.verticalHeaderItem(2)
        item.setText(_translate("laonSearch", "3"))
        item = self.loan.verticalHeaderItem(3)
        item.setText(_translate("laonSearch", "4"))
        item = self.loan.verticalHeaderItem(4)
        item.setText(_translate("laonSearch", "5"))
        item = self.loan.horizontalHeaderItem(0)
        item.setText(_translate("laonSearch", "贷款号"))
        item = self.loan.horizontalHeaderItem(1)
        item.setText(_translate("laonSearch", "发放机构"))
        item = self.loan.horizontalHeaderItem(2)
        item.setText(_translate("laonSearch", "贷款金额"))
        item = self.loan.horizontalHeaderItem(3)
        item.setText(_translate("laonSearch", "已发放金额"))
        self.choice.setItemText(0, _translate("laonSearch", "贷款号"))
        self.choice.setItemText(1, _translate("laonSearch", "户主身份证"))
        self.label_4.setText(_translate("laonSearch", "贷款发放信息："))

