# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'accountSearch.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_accountSearch(object):
    def setupUi(self, accountSearch):
        accountSearch.setObjectName("accountSearch")
        accountSearch.resize(1098, 915)
        accountSearch.setStyleSheet("col")
        accountSearch.setStyleSheet("#accountSearch {border-image:url(./1.jpg);}")
        self.choice = QtWidgets.QComboBox(accountSearch)
        self.choice.setGeometry(QtCore.QRect(340, 100, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.choice.setFont(font)
        self.choice.setObjectName("choice")
        self.choice.addItem("")
        self.choice.addItem("")
        self.text = QtWidgets.QLineEdit(accountSearch)
        self.text.setGeometry(QtCore.QRect(480, 100, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text.setFont(font)
        self.text.setText("")
        self.text.setObjectName("text")
        self.Search = QtWidgets.QPushButton(accountSearch)
        self.Search.setGeometry(QtCore.QRect(730, 100, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Search.setFont(font)
        self.Search.setStyleSheet("color:rgb(200, 84, 6)")
        self.Search.setObjectName("Search")
        self.label = QtWidgets.QLabel(accountSearch)
        self.label.setGeometry(QtCore.QRect(500, 30, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("color:red")
        self.label.setObjectName("label")
        self.account = QtWidgets.QTableWidget(accountSearch)
        self.account.setGeometry(QtCore.QRect(30, 240, 1051, 291))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.account.setFont(font)
        self.account.setObjectName("account")
        self.account.setColumnCount(7)
        self.account.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.account.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.account.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.account.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.account.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.account.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.account.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.account.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.account.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.account.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.account.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.account.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.account.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.account.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.account.setItem(0, 1, item)
        self.account.horizontalHeader().setDefaultSectionSize(145)
        self.client = QtWidgets.QTableWidget(accountSearch)
        self.client.setGeometry(QtCore.QRect(30, 620, 1051, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.client.setFont(font)
        self.client.setObjectName("client")
        self.client.setColumnCount(4)
        self.client.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.client.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.client.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.client.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.client.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.client.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.client.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.client.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.client.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.client.setHorizontalHeaderItem(3, item)
        self.client.horizontalHeader().setDefaultSectionSize(200)
        self.label_2 = QtWidgets.QLabel(accountSearch)
        self.label_2.setGeometry(QtCore.QRect(500, 200, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(accountSearch)
        self.label_3.setGeometry(QtCore.QRect(500, 580, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.ts = QtWidgets.QLabel(accountSearch)
        self.ts.setGeometry(QtCore.QRect(360, 150, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ts.setFont(font)
        self.ts.setStyleSheet("color:red")
        self.ts.setText("")
        self.ts.setObjectName("ts")

        self.retranslateUi(accountSearch)
        QtCore.QMetaObject.connectSlotsByName(accountSearch)

    def retranslateUi(self, accountSearch):
        _translate = QtCore.QCoreApplication.translate
        accountSearch.setWindowTitle(_translate("accountSearch", "Dialog"))
        self.choice.setItemText(0, _translate("accountSearch", "账户号"))
        self.choice.setItemText(1, _translate("accountSearch", "户主身份证"))
        self.Search.setText(_translate("accountSearch", "搜索"))
        self.label.setText(_translate("accountSearch", "账户搜索"))
        item = self.account.verticalHeaderItem(0)
        item.setText(_translate("accountSearch", "1"))
        item = self.account.verticalHeaderItem(1)
        item.setText(_translate("accountSearch", "2"))
        item = self.account.verticalHeaderItem(2)
        item.setText(_translate("accountSearch", "3"))
        item = self.account.verticalHeaderItem(3)
        item.setText(_translate("accountSearch", "4"))
        item = self.account.verticalHeaderItem(4)
        item.setText(_translate("accountSearch", "5"))
        item = self.account.horizontalHeaderItem(0)
        item.setText(_translate("accountSearch", "账户号"))
        item = self.account.horizontalHeaderItem(1)
        item.setText(_translate("accountSearch", "账户类型"))
        item = self.account.horizontalHeaderItem(2)
        item.setText(_translate("accountSearch", "余额"))
        item = self.account.horizontalHeaderItem(3)
        item.setText(_translate("accountSearch", "所属支行"))
        item = self.account.horizontalHeaderItem(4)
        item.setText(_translate("accountSearch", "开户日期"))
        item = self.account.horizontalHeaderItem(5)
        item.setText(_translate("accountSearch", "货币类型"))
        item = self.account.horizontalHeaderItem(6)
        item.setText(_translate("accountSearch", "透支额度/利率"))
        __sortingEnabled = self.account.isSortingEnabled()
        self.account.setSortingEnabled(False)
        self.account.setSortingEnabled(__sortingEnabled)
        item = self.client.verticalHeaderItem(0)
        item.setText(_translate("accountSearch", "1"))
        item = self.client.verticalHeaderItem(1)
        item.setText(_translate("accountSearch", "2"))
        item = self.client.verticalHeaderItem(2)
        item.setText(_translate("accountSearch", "3"))
        item = self.client.verticalHeaderItem(3)
        item.setText(_translate("accountSearch", "4"))
        item = self.client.verticalHeaderItem(4)
        item.setText(_translate("accountSearch", "5"))
        item = self.client.horizontalHeaderItem(0)
        item.setText(_translate("accountSearch", "账户号"))
        item = self.client.horizontalHeaderItem(1)
        item.setText(_translate("accountSearch", "户主1身份证"))
        item = self.client.horizontalHeaderItem(2)
        item.setText(_translate("accountSearch", "户主1姓名"))
        item = self.client.horizontalHeaderItem(3)
        item.setText(_translate("accountSearch", "户主2身份证"))
        self.label_2.setText(_translate("accountSearch", "账户信息："))
        self.label_3.setText(_translate("accountSearch", "户主信息："))
