# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'accountAdd.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addAccount(object):
    def setupUi(self, addAccount):
        addAccount.setObjectName("addAccount")
        addAccount.resize(447, 587)
        addAccount.setStyleSheet("#addAccount{border-image:url(./1.jpg);}")
        self.label_7 = QtWidgets.QLabel(addAccount)
        self.label_7.setGeometry(QtCore.QRect(40, 350, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.rate = QtWidgets.QLineEdit(addAccount)
        self.rate.setGeometry(QtCore.QRect(197, 308, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rate.setFont(font)
        self.rate.setObjectName("rate")
        self.label_6 = QtWidgets.QLabel(addAccount)
        self.label_6.setGeometry(QtCore.QRect(40, 264, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(addAccount)
        self.label_3.setGeometry(QtCore.QRect(43, 180, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.account_type = QtWidgets.QLineEdit(addAccount)
        self.account_type.setGeometry(QtCore.QRect(200, 138, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.account_type.setFont(font)
        self.account_type.setObjectName("account_type")
        self.label_8 = QtWidgets.QLabel(addAccount)
        self.label_8.setGeometry(QtCore.QRect(40, 388, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.overdraft = QtWidgets.QLineEdit(addAccount)
        self.overdraft.setGeometry(QtCore.QRect(197, 388, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.overdraft.setFont(font)
        self.overdraft.setObjectName("overdraft")
        self.id = QtWidgets.QLineEdit(addAccount)
        self.id.setGeometry(QtCore.QRect(200, 96, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.id.setFont(font)
        self.id.setText("")
        self.id.setObjectName("id")
        self.label_2 = QtWidgets.QLabel(addAccount)
        self.label_2.setGeometry(QtCore.QRect(43, 138, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_9 = QtWidgets.QLabel(addAccount)
        self.label_9.setGeometry(QtCore.QRect(40, 308, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(addAccount)
        self.label_4.setGeometry(QtCore.QRect(43, 222, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(addAccount)
        self.label_5.setGeometry(QtCore.QRect(180, 40, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.currency_type = QtWidgets.QLineEdit(addAccount)
        self.currency_type.setGeometry(QtCore.QRect(197, 350, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.currency_type.setFont(font)
        self.currency_type.setObjectName("currency_type")
        self.brance = QtWidgets.QLineEdit(addAccount)
        self.brance.setGeometry(QtCore.QRect(200, 222, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.brance.setFont(font)
        self.brance.setObjectName("brance")
        self.CreateBtn = QtWidgets.QPushButton(addAccount)
        self.CreateBtn.setGeometry(QtCore.QRect(200, 518, 221, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CreateBtn.setFont(font)
        self.CreateBtn.setAutoFillBackground(True)
        self.CreateBtn.setObjectName("CreateBtn")
        self.start_date = QtWidgets.QLineEdit(addAccount)
        self.start_date.setGeometry(QtCore.QRect(197, 264, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.start_date.setFont(font)
        self.start_date.setText("")
        self.start_date.setObjectName("start_date")
        self.label = QtWidgets.QLabel(addAccount)
        self.label.setGeometry(QtCore.QRect(43, 96, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.account_id = QtWidgets.QLineEdit(addAccount)
        self.account_id.setGeometry(QtCore.QRect(200, 180, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.account_id.setFont(font)
        self.account_id.setObjectName("account_id")

        self.retranslateUi(addAccount)
        QtCore.QMetaObject.connectSlotsByName(addAccount)

    def retranslateUi(self, addAccount):
        _translate = QtCore.QCoreApplication.translate
        addAccount.setWindowTitle(_translate("addAccount", "Dialog"))
        self.label_7.setText(_translate("addAccount", "货币类型（数字）"))
        self.label_6.setText(_translate("addAccount", "开户日期"))
        self.label_3.setText(_translate("addAccount", "账户号"))
        self.label_8.setText(_translate("addAccount", "透支额"))
        self.label_2.setText(_translate("addAccount", "账户类型（数字）"))
        self.label_9.setText(_translate("addAccount", "利率"))
        self.label_4.setText(_translate("addAccount", "余额"))
        self.label_5.setText(_translate("addAccount", "开户"))
        self.CreateBtn.setText(_translate("addAccount", "创建"))
        self.label.setText(_translate("addAccount", "户主身份证号"))
