# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'accountModify.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(793, 481)
        self.currency_type = QtWidgets.QLineEdit(Dialog)
        self.currency_type.setGeometry(QtCore.QRect(197, 180, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.currency_type.setFont(font)
        self.currency_type.setObjectName("currency_type")
        self.overdraft = QtWidgets.QLineEdit(Dialog)
        self.overdraft.setGeometry(QtCore.QRect(197, 300, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.overdraft.setFont(font)
        self.overdraft.setObjectName("overdraft")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(40, 300, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(43, 140, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 90, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(340, 40, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(43, 260, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.brance = QtWidgets.QLineEdit(Dialog)
        self.brance.setGeometry(QtCore.QRect(200, 260, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.brance.setFont(font)
        self.brance.setObjectName("brance")
        self.rate = QtWidgets.QLineEdit(Dialog)
        self.rate.setGeometry(QtCore.QRect(197, 220, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rate.setFont(font)
        self.rate.setObjectName("rate")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(40, 180, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.ModifyBtn = QtWidgets.QPushButton(Dialog)
        self.ModifyBtn.setGeometry(QtCore.QRect(200, 400, 221, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ModifyBtn.setFont(font)
        self.ModifyBtn.setAutoFillBackground(True)
        self.ModifyBtn.setObjectName("ModifyBtn")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(40, 220, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.account_id = QtWidgets.QLabel(Dialog)
        self.account_id.setGeometry(QtCore.QRect(201, 90, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.account_id.setFont(font)
        self.account_id.setObjectName("account_id")
        self.account_type = QtWidgets.QLabel(Dialog)
        self.account_type.setGeometry(QtCore.QRect(200, 140, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.account_type.setFont(font)
        self.account_type.setObjectName("account_type")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(490, 140, 261, 291))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.modify = QtWidgets.QPushButton(Dialog)
        self.modify.setGeometry(QtCore.QRect(580, 400, 93, 28))
        self.modify.setObjectName("modify")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(490, 90, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_8.setText(_translate("Dialog", "透支额"))
        self.label_2.setText(_translate("Dialog", "账户类型(数字)"))
        self.label_3.setText(_translate("Dialog", "账户号"))
        self.label_5.setText(_translate("Dialog", "修改账户"))
        self.label_4.setText(_translate("Dialog", "余额"))
        self.label_7.setText(_translate("Dialog", "货币类型（数字）"))
        self.ModifyBtn.setText(_translate("Dialog", "修改信息"))
        self.label_9.setText(_translate("Dialog", "利率"))
        self.account_id.setText(_translate("Dialog", "1"))
        self.account_type.setText(_translate("Dialog", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "姓名"))
        self.modify.setText(_translate("Dialog", "修改"))
        self.label_6.setText(_translate("Dialog", "账户持有者："))
